server:
  address: 127.0.0.1
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/mywebapp
    username: mywebapp
    password: mywebapp

  jpa:
    hibernate:
      ddl-auto: validate
